name: CI/CD
on: [push]
jobs:
  style_check_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        working-directory: api
        run: cargo clippy --all-targets --all-features
